# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

language: c

# Opt into fully virtualized infrastructure
# cf http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/
sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  ## PPA for Rcpp and some other packages
  - sudo add-apt-repository -y ppa:edd/misc
  ## r-travis by Craig Citro et al
  - curl -OL http://raw.github.com/eddelbuettel/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-rcpp r-cran-bh r-cran-knitr

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: kv1vuO9ZVHWedGJT7bSUkMziMv1eJVnLxKiJ/gsV3004CfzG8F5yEk6qNhneacMuRiSbngY32R8scUsrJO49xpIUEss57OVoukq0jk+/UM/GKABMYkFr6NFrHK9Yz1Q6mINbN75Li7pyFy04Ge48aqWsR+aXcC6Z4kbsig660s2Ygoh24p0tcRc0K854ellKYqQRBjyUsLh4lF++uHBCVI0BSbSszYaGB/jvTA+CDuIL9vXHdWgV6sCdLLqAyqxHOMdCFDMWuiNMPWD0cikk2JlPcMWcbI9MBzjworl8yyp5PSc4oTmx36zoBd+UvC71WcOJZKYQxXSJg7uPoYQ6QOhbeRW3ehfRi0lb7IP+8Ui12Xj9Y1mtAjPz1vGYqtLXYYmWAc346VTUJAC79f91ZICOZLIyI8nugRSJqzPfdXIETDPIPFZ0AekgXaIiR5DT3rPndxuucdQgvzI4x0lFfQklLgzKXeVEV3F3GWa/JZSQGqpwv4lPoK7pJ8i6uXZpLouxtYscUTPqlFngaMmngOAzudZeghDIgMRRZdkI7DTio4mU2YIW256eRTf6kRHuqQ9yVabH3gys/kuVH4goUojnfH4JF1uQ8xTWwvdvygmNZpH+Y7KHfkCHheJBr7oYVGy5bw9Q+Fe1NI+El7ATZrNfUpW5cBouc8Ipimkhdb0=

